##server#
server: 
  port: 8888
  tomcat: 
    maxThreads: 100
    minSpareThreads: 50
    maxConnections: 10000
    acceptCount: 1000
  servlet: 
    context-path: /admin
##profile
spring:
  profiles:
    active: dev
##swagger2 enable
swagger: 
  enable: true
##datasource config#
datasource:
  #read-write#
  rw: 
    url: jdbc:mysql://mldb.ml.com:3306/mnc_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=CST
    username: mnc_dev
    password: 123456
  #only read#
  r: 
    url: jdbc:mysql://mldb.ml.com:3306/mnc_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=CST
    username: mnc_dev
    password: 123456
##redis config#
redis: 
  host: redis.ml.com
  port: 6379
  pass: 123456
  database: 6
  pool: 
    maxWaitMillis: 0
##eureka##
eureka: 
  client: 
    service-url: 
      defaultZone: http://src-dev.ml.com/src/eureka
management:
  endpoint: 
    beans: 
      enabled: false
    health: 
      show-details: ALWAYS
  endpoints: 
    web: 
      exposure: 
        include: "*"
#        exclude: env,beans,scheduledtasks,configprops,loggers,httptrace
##rabbitMq config
rabbitmq: 
  host: devmq.ml.com
  port: 5672
  username: wintel
  password: wintel
  receive-timeout: 1000
  reply-timeout: 1000

##okhttp
okhttp:
  client:
    connectTimeout: 15000
    readTimeout: 1500
    threadPool:
      coreThreadSize:
      maxThreadSize:
      threadKeepAliveTime:
    dispatcher:
      maxRequests: 64
      maxRequestsPerHost: 5
